---
- name: Install nvm {{ nvm_version }}
  ansible.builtin.git:
    repo: "{{ nvm_git_repository }}"
    recursive: "{{ nvm_git_recursive }}"
    dest: "{{ nvm_install_path }}"
    version: "v{{ nvm_version }}"
    force: "{{ nvm_force_install | bool }}"
  when: nvm_version | regex_search('\\d.')

- name: Install nvm latest
  ansible.builtin.git:
    repo: "{{ nvm_git_repository }}"
    recursive: "{{ nvm_git_recursive }}"
    dest: "{{ nvm_install_path }}"
    version: "{% if nvm_version == 'latest' %}master{% else %}{{ nvm_version }}{% endif %}"
    force: "{{ nvm_force_install | bool }}"
  when: nvm_version | regex_search('master|HEAD|latest')
