---
exclude_paths:
  - .ansible
  - roles/stephdewit.nvm
  - roles/staticdev.pyenv
  - roles/gantsign.golang
  - roles/deekayen.awscli2
  - roles/rolehippie.starship
  - collections/ansible_collections

enable_list:
  - yaml
