---
collections:
  - name: manala.roles
    version: 3.7.0
  - name: community.general
    version: 9.4.0

roles:
  - name: staticdev.pyenv
    version: 2.10.2
  - name: deekayen.awscli2
    version: 1.1.0
  - name: gantsign.golang
    version: 3.3.2
  - name: rolehippie.starship
    version: v2.6.0
