---
collections:
  - name: manala.roles
    version: 3.7.0
  - name: community.general
    version: 9.4.0

roles:
  - name: diodonfrost.p10k
    version: 1.4.0
  - name: staticdev.pyenv
    version: 2.10.2
  - name: stephdewit.nvm
    version: v3.4.0
  - name: deekayen.awscli2
    version: 1.1.0
  - name: gantsign.golang
    version: 3.3.2
