---
apt_keys:
  - url: https://dl.google.com/linux/linux_signing_key.pub
    keyring: /etc/apt/trusted.gpg.d/google-chrome.gpg

  - url: https://apt.releases.hashicorp.com/gpg
    keyring: /etc/apt/trusted.gpg.d/hashicorp.gpg

  - url: https://download.spotify.com/debian/pubkey_C85668DF69375001.gpg
    keyring: /etc/apt/trusted.gpg.d/spotify.gpg

  - url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

  - url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    keyring: /etc/apt/trusted.gpg.d/kubernetes.gpg

  - url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /etc/apt/trusted.gpg.d/1password.gpg

  - url: https://baltocdn.com/helm/signing.asc
    keyring: /etc/apt/trusted.gpg.d/helm.gpg

  - url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/vscode.gpg

  - url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    keyring: /etc/apt/trusted.gpg.d/tailscale.gpg

  - url: https://keyserver.ubuntu.com/pks/lookup?op=get&search=0x9461999446FAF0DF770BFC9AE58A9D36647CAE7F
    keyring: /etc/apt/trusted.gpg.d/papirus.gpg

  - url: https://aquasecurity.github.io/trivy-repo/deb/public.key
    keyring: /etc/apt/trusted.gpg.d/trivy.gpg

  - url: https://raw.githubusercontent.com/eza-community/eza/main/deb.asc
    keyring: /etc/apt/trusted.gpg.d/gierens.gpg

  - url: https://www.virtualbox.org/download/oracle_vbox_2016.asc
    keyring: /etc/apt/trusted.gpg.d/virtualbox.gpg

apt_repos:
  - filename: google-chrome
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/hashicorp.gpg] https://apt.releases.hashicorp.com noble main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/spotify.gpg] https://repository.spotify.com stable non-free
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu noble stable
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
  - filename: 1password
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/1password.gpg] https://downloads.1password.com/linux/debian/amd64 stable main
  - filename: vscode
    repo: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/vscode.gpg] https://packages.microsoft.com/repos/code stable main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/tailscale.gpg] https://pkgs.tailscale.com/stable/ubuntu noble main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/papirus.gpg] http://ppa.launchpad.net/papirus/papirus/ubuntu noble main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/trivy.gpg] https://aquasecurity.github.io/trivy-repo/deb generic main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/gierens.gpg] http://deb.gierens.de stable main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/virtualbox.gpg] https://download.virtualbox.org/virtualbox/debian noble contrib

apt_install:
  - 1password
  - asciinema
  - bat
  - code
  - containerd.io
  - direnv
  - docker-buildx-plugin
  - docker-ce
  - docker-ce-cli
  - docker-compose-plugin
  - eza
  - ffmpeg
  - fzf
  - google-chrome-stable
  - helm
  - imagemagick
  - jq
  - kamoso
  - kdeconnect
  - kubectl
  - kwin-bismuth
  - latte-dock
  - make
  - openssh-server
  - papirus-icon-theme
  - simplescreenrecorder
  - spotify-client
  - sshuttle
  - stow
  - tailscale
  - terraform
  - trivy
  - virtualbox-7.0
  - zsh

snap_install:
  - asciinema-agg
  - dbeaver-ce
  - filelight
  - kdenlive
  - obsidian
  - slack
  - yq

snap_classic:
  - obsidian

manala_ohmyzsh_dir: "{{ ansible_env.HOME }}/.oh-my-zsh"
manala_ohmyzsh:
  update: true

# custom plugins
zsh_plugins:
  - repo: https://github.com/Aloxaf/fzf-tab
    dest: "{{ manala_ohmyzsh_dir }}/custom/plugins/fzf-tab"
    version: v1.2.0

pyenv_version: HEAD
pyenv_virtualenv_version: HEAD
pyenv_update_version: HEAD
pyenv_update: true
pyenv_path: "{{ ansible_env.HOME }}/.pyenv"
pyenv_shellrc_file: ~/.zshrc
pyenv_python_versions:
  - 3.11.4
  - 3.12.10
  - 3.13.3
pyenv_global:
  - 3.13.3

nvm_version: 0.39.3
nvm_node_version: lts
nvm_install_path: ~/.nvm
nvm_install_deps: true

git_username: "Campbell Whitworth"
git_email: "campbell.whitworth@fingermarkglobal.com"

k9s_version: v0.50.9

atuin_version: v18.8.0
