---
apt_keys:
  - url: https://dl.google.com/linux/linux_signing_key.pub
    keyring: /etc/apt/trusted.gpg.d/google-chrome.gpg

  - url: https://apt.releases.hashicorp.com/gpg
    keyring: /etc/apt/trusted.gpg.d/hashicorp.gpg

  - url: https://download.spotify.com/debian/pubkey_7A3A762FAFD4A51F.gpg
    keyring: /etc/apt/trusted.gpg.d/spotify.gpg

  - url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /etc/apt/trusted.gpg.d/docker.gpg

  - url: https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key
    keyring: /etc/apt/trusted.gpg.d/kubernetes.gpg

  - url: https://downloads.1password.com/linux/keys/1password.asc
    keyring: /etc/apt/trusted.gpg.d/1password.gpg

  - url: https://baltocdn.com/helm/signing.asc
    keyring: /etc/apt/trusted.gpg.d/helm.gpg

  - url: https://packages.microsoft.com/keys/microsoft.asc
    keyring: /etc/apt/trusted.gpg.d/vscode.gpg

  - url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
    keyring: /etc/apt/trusted.gpg.d/tailscale.gpg

apt_repos:
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/hashicorp.gpg] https://apt.releases.hashicorp.com jammy main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/spotify.gpg] http://repository.spotify.com stable non-free
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu jammy stable
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/kubernetes.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/1password.gpg] https://downloads.1password.com/linux/debian/amd64 stable main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/vscode.gpg] https://packages.microsoft.com/repos/code stable main
  - deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/tailscale.gpg] https://pkgs.tailscale.com/stable/ubuntu jammy main

apt_install:
  - terraform
  - google-chrome-stable
  - spotify-client
  - docker-ce
  - docker-ce-cli
  - docker-buildx-plugin
  - docker-compose-plugin
  - containerd.io
  - 1password
  - kubectl
  - helm
  - code
  - tailscale

snap_install:
  - slack
