---
- name: General configuration
  hosts: localhost
  tasks:
    - name: Configure docker and ssh key for {{ ansible_user_id }}
      tags: user
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: [docker]
        append: true
        generate_ssh_key: true
        ssh_key_comment: "{{ ansible_user_id }}@{{ ansible_hostname }}"
      become: true

    - name: Enable passwordless sudo for {{ ansible_user_id }}
      tags: user
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/{{ ansible_user_id }}
        line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
        create: true
        mode: "0440"
      become: true

    - name: Configure git
      tags: git
      community.general.git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      loop:
        - name: user.name
          value: "{{ git_username }}"
        - name: user.email
          value: "{{ git_email }}"

    - name: Configure Konsave
      tags: konsave
      ansible.builtin.copy:
        src: "files/konsave/conf.yaml"
        dest: "{{ ansible_env.HOME }}/.config/konsave/conf.yaml"
        mode: "0644"
