---
- name: General configuration
  hosts: localhost
  tasks:
    - name: Ensure ~/.local/bin exists
      tags: user
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: "0755"

    - name: Symlink batcat to bat
      tags: user
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: "{{ ansible_env.HOME }}/.local/bin/bat"
        state: link

    - name: Configure docker and ssh key for {{ ansible_user_id }}
      tags: user
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: [docker]
        append: true
        generate_ssh_key: true
        ssh_key_comment: "{{ ansible_user_id }}@{{ ansible_hostname }}"
        force: false
      become: true

    - name: Enable passwordless sudo for {{ ansible_user_id }}
      tags: user
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/{{ ansible_user_id }}
        line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
        create: true
        mode: "0440"
      become: true

    - name: Make Konsave directory
      tags: konsave
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.config/konsave"
        state: directory
        mode: "0755"

    - name: Configure Konsave
      tags: konsave
      ansible.builtin.copy:
        src: "files/konsave/conf.yaml"
        dest: "{{ ansible_env.HOME }}/.config/konsave/conf.yaml"
        mode: "0644"
