---
- name: General configuration
  hosts: localhost
  tasks:
    - name: Ensure ~/.local/bin exists
      tags: user
      ansible.builtin.file:
        path: "{{ ansible_env.HOME }}/.local/bin"
        state: directory
        mode: "0755"

    - name: Symlink batcat to bat
      tags: user
      ansible.builtin.file:
        src: /usr/bin/batcat
        dest: "{{ ansible_env.HOME }}/.local/bin/bat"
        state: link

    - name: Configure docker and ssh key for {{ ansible_user_id }}
      tags: user
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: [docker]
        append: true
        generate_ssh_key: true
        ssh_key_comment: "{{ ansible_user_id }}@{{ ansible_hostname }}"
        force: false
      become: true

    - name: Enable passwordless sudo for {{ ansible_user_id }}
      tags: user
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/{{ ansible_user_id }}
        line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
        create: true
        mode: "0440"
      become: true

    - name: Clone Dotfiles repository
      ansible.builtin.git:
        repo: git@github.com:clueshh/dotfiles.git
        dest: "{{ ansible_env.HOME }}/.dotfiles"
        version: master

    - name: Create symlinks for dotfiles
      ansible.builtin.command:
        cmd: make stow
      changed_when: false
      args:
        chdir: "{{ ansible_env.HOME }}/.dotfiles"
