---
- name: General configuration
  hosts: localhost
  tasks:
    - name: Enable passwordless sudo for {{ ansible_user_id }}
      tags: sudo
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/{{ ansible_user_id }}
        line: "{{ ansible_user_id }} ALL=(ALL) NOPASSWD:ALL"
        validate: "visudo -cf %s"
        create: true
        mode: "0440"
      become: true

    - name: Configure git
      tags: git
      community.general.git_config:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        scope: global
      loop:
        - name: user.name
          value: "{{ git_username }}"
        - name: user.email
          value: "{{ git_email }}"

    - name: Add Latte Dock config
      tags: latte-dock
      ansible.builtin.copy:
        src: "files/latte-dock/Campbell.layout.latte"
        dest: "{{ ansible_env.HOME }}/.config/latte/templates/Campbell.layout.latte"
        mode: "0644"

    - name: Add Konsole config
      tags: konsole
      ansible.builtin.copy:
        src: "files/konsole/campbell.profile"
        dest: "{{ ansible_env.HOME }}/.local/share/konsole/campbell.profile"
        mode: "0644"
