---
- name: Install local laptop requirements
  hosts: localhost
  tags: [install]
  tasks:
    - name: Always gather facts (incase run with tags)
      ansible.builtin.setup:
      tags: always

    - name: Add apt keys
      tags: apt-repo-key
      ansible.builtin.apt_key:
        url: "{{ item.url }}"
        keyring: "{{ item.keyring }}"
        state: present
      become: true
      loop: "{{ apt_keys }}"

    - name: Add apt repos
      tags: apt-repo
      ansible.builtin.apt_repository:
        repo: "{{ item }}"
        state: present
      become: true
      loop: "{{ apt_repos }}"
      when: item is string

    - name: Add apt repos (with filename)
      tags: apt-repo
      ansible.builtin.apt_repository:
        repo: "{{ item.repo }}"
        filename: "{{ item.filename }}"
        state: present
      become: true
      loop: "{{ apt_repos }}"
      when: item is mapping

    - name: Apt install software
      tags: [software-install, apt]
      ansible.builtin.apt:
        state: present
        name: "{{ item }}"
      become: true
      loop: "{{ apt_install }}"

    - name: Apt install k9s
      tags: [software-install, apt, k9s]
      ansible.builtin.apt:
        state: present
        deb: "https://github.com/derailed/k9s/releases/download/{{ k9s_version }}/k9s_linux_amd64.deb"
      become: true

    - name: Snap install software
      tags: [software-install, snap]
      community.general.snap:
        state: present
        name: "{{ item }}"
      become: true
      loop: "{{ snap_install }}"

    - name: Find all .desktop files in snap installed apps
      tags: [software-install, snap]
      ansible.builtin.find:
        recurse: false
        paths: /var/lib/snapd/desktop/applications/
        patterns: "*.desktop"
      register: find

    - name: Link snap installed apps to /usr/share/applications
      tags: [software-install, snap]
      ansible.builtin.file:
        src: "{{ item.path }}"
        path: "/usr/share/applications/{{ item.path | basename }}"
        state: link
      become: true
      loop: "{{ find.files }}"

    - name: Check if aws binary is in PATH
      tags: [software-install, awscli]
      ansible.builtin.command: which aws
      changed_when: aws_path.rc != 0
      register: aws_path
      ignore_errors: true

    - name: Install aws cli
      tags: [software-install, awscli]
      ansible.builtin.import_role:
        name: deekayen.awscli2
      when: aws_path.rc != 0

    - name: Install oh-my-zsh
      tags: [zsh, ohmyzsh]
      ansible.builtin.import_role:
        name: manala.roles.ohmyzsh
      become: true

    - name: Install p10k
      tags: [zsh, p10k]
      ansible.builtin.import_role:
        name: diodonfrost.p10k
      become: true

    - name: Overwrite .p10k.zsh
      tags: [zsh, p10k, p10k-zsh]
      ansible.builtin.copy:
        src: "files/p10k/.p10k.zsh"
        dest: "{{ ansible_env.HOME }}/.p10k.zsh"
        mode: "0644"

    - name: Install nvm
      tags: nvm
      ansible.builtin.import_role:
        name: stephdewit.nvm

    - name: Install pyenv
      tags: pyenv
      ansible.builtin.import_role:
        name: staticdev.pyenv

    - name: Install golang
      tags: golang
      ansible.builtin.import_role:
        name: gantsign.golang

    - name: Install Consolas ligaturized fonts for vscode
      tags: fonts
      ansible.builtin.copy:
        src: "files/fonts/{{ item }}"
        dest: "{{ fonts_path | default('/usr/share/fonts/TTF') }}/{{ item }}"
        mode: "0644"
      become: true
      loop:
        - Consolasligaturizedv3-Bold.ttf
        - Consolasligaturizedv3-BoldItalic.ttf
        - Consolasligaturizedv3-Italic.ttf
        - Consolasligaturizedv3.ttf

- name: Configure general
  tags: [configure, general-config]
  ansible.builtin.import_playbook: general-config.yaml

- name: System update
  hosts: localhost
  tags: software-update-all
  tasks:
    - name: Apt update all packages
      ansible.builtin.apt:
        update_cache: true
        name: "*"
        state: latest
        only_upgrade: true
      become: true
